---
title: "progress-report-hedgreneric"
author: "Eric Hedgren"
date: "2023-11-16"
output: html_document
---

```{r}
library(Lahman)
library(tidyverse)
head(HallOfFame, 3)
```

```{r}
HallOfFame %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2022))
```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)

head(tables[[1]], 3)
write.csv(tables[[1]], "temp.csv", row.names=FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types =FALSE)
head(backin, 3)
```

```{r}
head(tables)
```
```{r}
colnames(HallOfFame)
```
```{r}
HallOfFame
```


```{r}
readr::parse_number(c("34%", "10th", "1.0"))
```
```{r}
x <- c("David Ortiz", "X-Barry Bonds", "X-Roger Clemens")
gsub("X-", "", x)
```

```{r}
x1 <- data.frame(id=1:2, name=c("A", "B"))
x2 <- data.frame(id=3:4, name=c("C", "D"))
rbind(x1, x2)
```

```{r}
dframe <- rbind(x1, x2)
write.csv(dframe, file="some-file.csv", row.names = FALSE)
readr::write_csv(dframe, file="some-other-file.csv")
```

