---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Lab report #4 - instructions

```{r}
# install.packages("Lahman")
library(Lahman)

head(HallOfFame, 3)
str(HallOfFame)
# hf <- HallOfFame
```

```{r}

library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)

head(tables[[1]], 3)
```

Took a while to figure out how to change from TRUE and FALS statements to a Y or N to mark if the player was inducted into the hall of fame. Had to add all of the columns to combine the two smoothly.
```{r}

write.csv(tables[[1]], "temp.csv", row.names=FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types =FALSE)
head(backin, 3)
backin$needed <- 292
backin$inducted <- (backin$Votes > backin$needed)
backin$Name <- gsub("X-", "", backin$Name)

matchedData <- data.frame(
  playerID = backin$Name,
  yearID = 2023,
  votedBy = "BBWAA",
  ballots = 389,
  needed = 292,
  votes = as.integer(backin$Votes),
  inducted = ifelse(backin$inducted == TRUE,"Y","N"),
  category = "Player",
  needed_note = NA

)

dframe <- rbind(HallOfFame, matchedData)

```
Exporting to CSV file
```{r}
write_csv(dframe, file = "combinedData.csv")
```
